package view;

import java.awt.Image;

/**
 * Represents the interactive View of the program.Specifies the operations that any Interactive GUI
 * should provide.
 */
public interface ImageView {

  /**
   * Sets the actions to be taken by the view using any implementation of the {@link Features}
   * interface.
   *
   * @param operations a implementation of the {@link Features} interface
   */
  void setFeatures(Features operations);

  /**
   * Displays the image that is currently being worked with, loaded or generated by the user.
   *
   * @param image to be displayed
   */
  void showImage(Image image);

  /**
   * Displays the error message whenever a wrong input is given.
   *
   * @param message error message to be displayed
   */
  void showError(String message);

}
